### ISSUE TITLE
[help] checkpoint&log

### ISSUE THREAD

**Issue by Ezra-Yu** [bofen97/RepVGG-openMMLab#1]
Can you attach your checkpoint and training log？

**Comment by bofen97** [comment]
Because the training process is not using mmcls tools/train, there are no logs and checkpoints generated by mmcls tools/train. so I only uploaded the trained parameters to Google drive，but  the training code will be uploaded later  : )

**Comment by Ezra-Yu** [comment]
OK, thank you very much....
